---
title: 'Risky Visual Search - Choice Analysis'
author: 'Dave Braun'
date: 'December 13, 2022'
output:
  html_document:
    theme: flatly
    code_folding: hide
    df_print: paged
    toc: true
    includes:
      after_body: ../../../../html/footer.html
      in_header: ../../../../html/favicon.html
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(inputFile,
    encoding = encoding,
    output_file = 'index.html')})
---


This document was last updated at `r Sys.time()`.

```{r include = FALSE}
library(tidyverse)
library(ggsci)
library(gridExtra)
```


```{r}
d <- read.csv('../../../data/main_timing.csv')
N <- length(unique(d$subject))
head(d)
```

Initial sample size is `r N`.
```{r}
d <- d %>% 
  mutate(direction = recode(direction, `Easier than Reference` = 'Easier',
                          `Harder than Reference` = 'Harder'))
```


```{r}
p1 <- d %>% 
  group_by(subject, direction, delay) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction, delay) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N)) %>% 
    print() %>% 
  ggplot(aes(x = delay, y = ssd)) + 
  geom_hline(yintercept = .5, linetype = 'dotted') +
  geom_bar(stat = 'identity', aes(fill = direction), position = position_dodge(width= .9), color = 'black') + 
  geom_errorbar(aes(ymin = ssd - se, ymax = ssd + se, group = direction), width = .5, position = position_dodge(width= .9)) + 
  ylim(0,1) + 
  labs(
    x = 'Delay',
    y = 'Proportion Selection of Safe Deck',
    fill = 'Framing',
    caption = paste0('N = ', N, '.')
  ) + 
  scale_fill_manual(values = c(`Easier` = 'grey', `Harder` = 'white')) + 
  theme_bw() +
  theme(axis.ticks = element_blank(),
        panel.grid = element_blank(),
        strip.background = element_blank(),
        legend.position = c(.2, .85))
p1
```

### Individual differences in direction effect

```{r}
m <- d %>% 
  group_by(subject, direction, delay) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction, delay) %>% 
  summarize(ssd = mean(ssd_))

p2 <- d %>% 
    group_by(subject, direction, delay) %>% 
    summarize(ssd = mean(ssd)) %>% 
    mutate(delay = recode(delay, `Enforced` = 'Delay Enforced',
                           `Not Enforced` = 'Delay not Enforced')) %>% 
    ggplot(aes(x = direction, y = ssd)) + 
    geom_violin(fill = 'steelblue', alpha = .2) + 
    geom_boxplot(fill = NA) + 
    geom_jitter(width = .05, alpha = .7) + 
    geom_line(aes(group = subject), linetype = 'dashed', alpha = .7) +
    facet_wrap(~delay) +
    ylim(0,1) +
    labs(
    x = 'Framing',
    y = 'Proportion Selection of Safe Option'
    ) + 
    theme_bw() + 
    theme(strip.background = element_rect(color = 'black', fill = 'white'),
          axis.ticks = element_blank(),
          panel.grid = element_blank())

p2

```

```{r}
grid.arrange(p1, p2, nrow = 1)
```


```{r}
library(ez)

ad <- d %>% 
  group_by(subject, direction, magnitude, delay) %>% 
  summarize(ssd_ = mean(ssd)) 

m1 <- ezANOVA(wid = subject, within = .(direction, magnitude),
              between = .(delay), dv = ssd_, detailed = TRUE, data = ad)
cbind(m1$ANOVA, data.frame(n2p = m1$ANOVA$SSn / (m1$ANOVA$SSn + m1$ANOVA$SSd)))
  
```

## Marginal means

```{r eval = FALSE}
d %>% 
  group_by(subject, direction, magnitude, delay) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N))

d %>% 
  group_by(subject, direction, magnitude, delay) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(magnitude) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N))

d %>% 
  group_by(subject, direction, magnitude, delay) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(delay) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N))
```



## Mixed modeling

```{r}
library(lme4)

d$direction_e <- ifelse(d$direction == 'Easier', -0.5, 0.5)
d$delay_e <- ifelse(d$delay == 'Enforced', 0.5, -0.5)

# mm1 <- glmer(ssd ~ direction_e * delay_e + (1 + direction_e * delay_e | subject), data = d, family = binomial(link = 'logit'), nAGQ = 1)
# 
# mm1a <- glmer(ssd ~ direction_e * delay_e +
#                 (1 | subject) +
#                 (0 + direction_e + delay_e + direction_e:delay_e| subject),
#                  data = d, family = binomial(link = 'logit'), nAGQ = 1)
# 
# mm1b <- glmer(ssd ~ direction_e * delay_e +
#                 (1 | subject) +
#                 (0 + direction_e + delay_e | subject) +
#                 (0 + direction_e:delay_e | subject),
#                  data = d, family = binomial(link = 'logit'), nAGQ = 1)
# 
# 
# mm2 <- glmer(ssd ~ direction_e * delay_e + (1 + direction_e + delay_e | subject), data = d, family = binomial(link = 'logit'), nAGQ = 1)

## winning model
mm3 <- glmer(ssd ~ direction_e * delay_e + (1 | subject) + (0 + direction_e | subject), data = d, family = binomial(link = 'logit'), nAGQ = 1)

#mm4 <- glmer(ssd ~ direction_e * delay_e + (1 | subject), data = d, family = binomial(link = 'logit'), nAGQ = 1)

#anova(mm3, mm4)

mm <- mm3

```

### Hypothesis testing
```{r}
## hypothesis testing
summary(mm)
exp(fixef(mm))
exp(confint(mm, method = 'Wald'))


## direction var
mm2 <- glmer(ssd ~ delay_e + delay_e:direction_e  + 
               (1 | subject) +
               (0 + direction_e | subject), 
             data = d, family = binomial(link = 'logit'), nAGQ = 1)
anova(mm, mm2)

## delay var
mm2 <- glmer(ssd ~ direction_e + delay_e:direction_e  + 
               (1 | subject) +
               (0 + direction_e | subject), 
             data = d, family = binomial(link = 'logit'), nAGQ = 1)
anova(mm, mm2)

## interaction
mm2 <- glmer(ssd ~ direction_e + delay_e  + 
               (1 | subject) +
               (0 + direction_e | subject), 
             data = d, family = binomial(link = 'logit'), nAGQ = 1)
anova(mm, mm2)
```


### Prediction

```{r eval = FALSE}
easyPredCI <- function(model,newdata=NULL,alpha=0.05) {
    ## baseline prediction, on the linear predictor (logit) scale:
    pred0 <- predict(model,re.form=NA,newdata=newdata)
    ## fixed-effects model matrix for new data
    X <- model.matrix(formula(model,fixed.only=TRUE)[-2],newdata)
    beta <- fixef(model) ## fixed-effects coefficients
    V <- vcov(model)     ## variance-covariance matrix of beta
    pred.se <- sqrt(diag(X %*% V %*% t(X))) ## std errors of predictions
    ## inverse-link function
    linkinv <- family(model)$linkinv
    ## construct 95% Normal CIs on the link scale and
    ##  transform back to the response (probability) scale:
    crit <- -qnorm(alpha/2)
    linkinv(cbind(conf.low=pred0-crit*pred.se,
                  conf.high=pred0+crit*pred.se))
}


## prediction
## intervals from: https://stats.stackexchange.com/questions/147836/prediction-interval-for-lmer-mixed-effects-model-in-r
## dunno how to only get population-level prediction intervals from ^
#library(merTools)
test_data <- expand.grid(direction_e = unique(d$direction_e))
test_data$proba <- predict(mm1, re.form=NA, newdata = test_data, type='response')
test_data <- cbind(test_data, easyPredCI(mm1, newdata = test_data))
test_data %>% 
  ggplot(aes(x = direction, y = proba)) + 
  geom_bar(stat = 'identity') + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = .5) +
  ylim(0, 1) + 
  labs(
    x = 'Direction', 
    y = 'Probability of Selecting Safe Deck'
  ) + 
  theme_bw()
```














