---
title: 'Risky Visual Search - Experiment 1 Visual Search'
author: 'Dave Braun'
date: February 15, 2022
output:
  html_document:
    theme: flatly
    code_folding: hide
    df_print: paged
    toc: true
    after_body: ../../footer.html
    in_header: ../../favicon.html
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(inputFile,
    encoding = encoding,
    output_file = 'index.html')})
---


This document was last updated at `r Sys.time()`.

Here I'm doing a basic breakdown of expected visual search effects.

```{r include = FALSE}
library(tidyverse)
```


```{r}
d <- read.csv('../../data/pilot/exp1_main.csv')
N <- length(unique(d$subject))
head(d)
```
There were `r N` participants in this study.

```{r}
d %>% 
  group_by(subject, present_or_absent, n_stimuli) %>% 
  summarize(searchRt = mean(searchRt)) %>% 
  group_by(present_or_absent, n_stimuli) %>% 
  summarize(search_rt = mean(searchRt), se = sd(searchRt) / sqrt(N)) %>% 
  ggplot(aes(x = factor(n_stimuli), y = search_rt, group = present_or_absent)) + 
  geom_line(aes(color = present_or_absent)) + 
  geom_ribbon(aes(ymin = search_rt - se, ymax = search_rt + se, fill = present_or_absent), alpha = .3) + 
  labs(
    x = 'Number of Stimuli',
    y = 'Search RT (ms)',
    fill = 'Target',
    color = 'Target'
  ) + 
  theme_bw() + 
  theme(legend.position = c(.1,.8))
```


```{r}
d %>% 
  group_by(subject, present_or_absent, n_stimuli) %>% 
  summarize(error_ = mean(error)) %>% 
  group_by(present_or_absent, n_stimuli) %>% 
  summarize(error = mean(error_), se = sd(error_) / sqrt(N)) %>% 
  ggplot(aes(x = factor(n_stimuli), y = error, group = present_or_absent)) + 
  geom_line(aes(color = present_or_absent)) + 
  geom_ribbon(aes(ymin = error - se, ymax = error + se, fill = present_or_absent), alpha = .3) + 
  labs(
    x = 'Number of Stimuli',
    y = 'Error Rate',
    fill = 'Target',
    color = 'Target'
  ) + 
  theme_bw() + 
  theme(legend.position = c(.1,.8))
```



























