---
title: 'Risky Visual Search - Experiment 1a Time Analysis'
author: 'Dave Braun'
date: '`r format(Sys.time(), "%b %d %Y, %H:%M:%S")`'
output:
  html_document:
    theme: flatly
    code_folding: hide
    df_print: paged
    toc: true
    includes:
      after_body: ../../../../html/footer.html
      in_header: ../../../../html/favicon.html
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(inputFile,
    encoding = encoding,
    output_file = 'index.html')})
---


This document was last updated at `r Sys.time()`.

```{r include = FALSE}
library(tidyverse)
```


```{r}
exp <- str_extract(getwd(), 'exp\\d[a-z]?')
d <- read.csv(paste0(here::here(), '/experiments/analysis/', exp, '/data/', exp, '_main_full.csv'))
N <- length(unique(d$subject))
head(d)
```

Sample size is `r N`. Note, because this is an exploratory analysis, I'm using *all* of the subjects.

# Basic Choice


```{r}
d %>% 
  group_by(subject, direction, magnitude) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction, magnitude) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N)) %>% 
  ggplot(aes(x = direction, y = ssd)) + 
  geom_bar(stat = 'identity', aes(fill = magnitude), position = position_dodge(width= .9)) + 
  geom_errorbar(aes(ymin = ssd - se, ymax = ssd + se, group = magnitude), width = .5, position = position_dodge(width= .9)) + 
  ylim(0,1) + 
  labs(
    x = 'Framing',
    y = 'Proportion Selection of Safe Deck',
    caption = paste0('N = ', N, '. N needed is 50.')
  ) + 
  theme_bw() 
```

## Individual differences in direction effect

```{r}
m <- d %>% 
  group_by(subject, direction) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction) %>% 
  summarize(ssd = mean(ssd_))

d %>% 
  group_by(subject, direction) %>% 
  summarize(ssd = mean(ssd)) %>% 
  ggplot(aes(x = direction, y = ssd)) + 
  geom_violin(fill = 'steelblue', alpha = .2) + 
  geom_boxplot(fill = NA) + 
  geom_jitter(width = .05, alpha = .7) + 
  geom_line(aes(group = subject), linetype = 'dashed', alpha = .7) +
  ylim(0,1) +
  labs(
    x = 'Direction',
    y = 'Proportion Selection of Safe Option'
  ) + 
  theme_bw()

```


# Choice Over Time

```{r}
## bin trials
trial_bins <- data.frame(trial = 1:308, bin = rep(1:28, each = 11))

d %>% 
  inner_join(trial_bins) %>% 
  group_by(subject, bin, direction) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(bin, direction) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N)) %>% 
  ggplot(aes(x = bin, y = ssd)) + 
  geom_ribbon(aes(ymin = ssd - se, ymax = ssd + se, fill = direction), alpha = .3) + 
  geom_line(aes(color = direction)) +
  labs(
    x = 'Trial Bin',
    y = 'Proportion Selection of Safe Deck',
    fill = 'Direction',
    color = 'Direction',
    caption = 'Each bin averages over 11 trials'
  ) + 
  ylim(0,1) + 
  theme_bw() + 
  theme(legend.position = 'bottom')
```



```{r}
d$trial_c <- d$trial - (max(d$trial) / 2)
m1 <- lm(ssd ~ trial_c * direction, data = d)
summary(m1)
```















