---
title: 'Risky Visual Search - Experiment 1 Preprocessing'
author: 'Dave Braun'
date: February 15, 2022
output:
  html_document:
    theme: flatly
    code_folding: hide
    df_print: paged
    toc: true
    after_body: ../../footer.html
    in_header: ../../favicon.html
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(inputFile,
    encoding = encoding,
    output_file = 'index.html')})
---


This document was last updated at `r Sys.time()`.

```{r include = FALSE}
library(tidyverse)
```


```{r}
d <- read.csv('../../data/pilot/exp1_main.csv')
head(d)
```


## Check runtimes

(mostly for adjusting after pilot)

```{r}
d %>% 
  group_by(subject) %>% 
  summarize(runtime = max(phase_runtime_mins)) %>% 
  ggplot(aes(x = reorder(subject, runtime), y = runtime)) + 
  geom_bar(stat = 'identity') +
  geom_hline(yintercept = 30, linetype = 'dashed') +
  labs(
    x = 'Subject',
    y = 'Main Phase Runtime (mins)'
  ) + 
  theme(axis.text.x = element_blank())
```

Going to take everyone under an hour and average as the completion time.

```{r}
runtimes <- d %>% 
  group_by(subject) %>% 
  summarize(runtime = max(phase_runtime_mins)) 
avg_runtime <- mean(runtimes[runtimes$runtime < 60,]$runtime)


desired_trials <- function(avg_runtime, n_trials = 500) {
  mins_per_trial <- avg_runtime / n_trials
  return(30 / mins_per_trial)
}

print(paste0('Target trials to be 30 min: ', round(desired_trials(avg_runtime))))
```



## Accuracy & Response Time

For visual search

```{r}
## rt distribution
d %>% 
  ggplot(aes(x = searchRt)) + 
  geom_histogram() + 
  facet_wrap(~subject, scales = 'free')

## gross rt threshold
d <- d[d$searchRt < 20000,]

d %>% 
  group_by(subject) %>% 
  summarize(accuracy = 1 - mean(error), rt = mean(searchRt)) %>% 
  ggplot(aes(x = rt/1000, y = accuracy, group = subject)) + 
  geom_point() + 
  labs(
    x = ' Average Response Time (s)',
    y = 'Average Accuracy'
  ) + 
  theme_bw()
```
























