---
title: 'Risky Visual Search - Experiment 1 Choice Analysis'
author: 'Dave Braun'
date: '`r format(Sys.time(), "%b %d %Y, %H:%M:%S")`'
output:
  html_document:
    theme: flatly
    code_folding: hide
    df_print: paged
    toc: true
    includes:
      after_body: ../../../../html/footer.html
      in_header: ../../../../html/favicon.html
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(inputFile,
    encoding = encoding,
    output_file = 'index.html')})
---


This document was last updated at `r Sys.time()`.

```{r include = FALSE}
library(tidyverse)
```


```{r}
exp <- str_extract(getwd(), 'exp\\d[a-z]?')
d <- read.csv(paste0(here::here(), '/experiments/analysis/', exp, '/data/', exp, '_main.csv'))
N <- length(unique(d$subject))
head(d)
```

Initial sample size is `r N`.


```{r}
d %>% 
  group_by(subject, direction, magnitude) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction, magnitude) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N)) %>% 
  ggplot(aes(x = direction, y = ssd)) + 
  geom_bar(stat = 'identity', aes(fill = magnitude), position = position_dodge(width= .9)) + 
  geom_errorbar(aes(ymin = ssd - se, ymax = ssd + se, group = magnitude), width = .5, position = position_dodge(width= .9)) + 
  ylim(0,1) + 
  labs(
    x = 'Framing',
    y = 'Proportion Selection of Safe Deck',
    caption = paste0('N = ', N, '. N needed is 50.')
  ) + 
  theme_bw() 
```

### Individual differences in direction effect

```{r}
m <- d %>% 
  group_by(subject, direction) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction) %>% 
  summarize(ssd = mean(ssd_))

d %>% 
  group_by(subject, direction) %>% 
  summarize(ssd = mean(ssd)) %>% 
  ggplot(aes(x = direction, y = ssd)) + 
  geom_violin(fill = 'steelblue', alpha = .2) + 
  geom_boxplot(fill = NA) + 
  geom_jitter(width = .05, alpha = .7) + 
  geom_line(aes(group = subject), linetype = 'dashed', alpha = .7) +
  ylim(0,1) +
  labs(
    x = 'Direction',
    y = 'Proportion Selection of Safe Option'
  ) + 
  theme_bw()

```



```{r}
ggsave('risky_visual_search.pdf', height = 5.5, width = 7.5)
ggsave('risy_visual_search.png', height = 720/96, width = 1280/96, dpi = 96, units = 'in')
```


```{r}
library(ez)

ad <- d %>% 
  mutate(ssd = 1 - selectedRiskyDeck) %>% 
  group_by(subject, direction, magnitude) %>% 
  summarize(ssd_ = mean(ssd)) 

m1 <- ezANOVA(wid = subject, within = .(direction, magnitude), dv = ssd_, detailed = TRUE, data = ad)
cbind(m1$ANOVA, data.frame(n2p = m1$ANOVA$SSn / (m1$ANOVA$SSn + m1$ANOVA$SSd)))
  
```

## Marginal means

```{r}
d %>% 
  group_by(subject, direction, magnitude) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(direction) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N))

d %>% 
  group_by(subject, direction, magnitude) %>% 
  summarize(ssd_ = mean(ssd)) %>% 
  group_by(magnitude) %>% 
  summarize(ssd = mean(ssd_), se = sd(ssd_) / sqrt(N))
```



## Mixed modeling

```{r}
library(lme4)
mm1 <- glmer(ssd ~ direction + (1 + direction | subject), data = d, family = binomial(link = 'logit'), nAGQ = 1)
## the simpler model fails to converge?
mm1a <- glmer(ssd ~ direction  + (1 | subject) + (0 + direction | subject), data = d, family = binomial(link = 'logit'), nAGQ = 1)
anova(mm1, mm1a)
```

### Hypothesis testing
```{r}
## hypothesis testing
mm2 <- glmer(ssd ~ 1  + (1 + direction | subject) , data = d, family = binomial(link = 'logit'), nAGQ = 1)
anova(mm1, mm2)
summary(mm1)
exp(fixef(mm1))
exp(confint(mm1, method = 'Wald'))
```

### Prediction

```{r}
easyPredCI <- function(model,newdata=NULL,alpha=0.05) {
    ## baseline prediction, on the linear predictor (logit) scale:
    pred0 <- predict(model,re.form=NA,newdata=newdata)
    ## fixed-effects model matrix for new data
    X <- model.matrix(formula(model,fixed.only=TRUE)[-2],newdata)
    beta <- fixef(model) ## fixed-effects coefficients
    V <- vcov(model)     ## variance-covariance matrix of beta
    pred.se <- sqrt(diag(X %*% V %*% t(X))) ## std errors of predictions
    ## inverse-link function
    linkinv <- family(model)$linkinv
    ## construct 95% Normal CIs on the link scale and
    ##  transform back to the response (probability) scale:
    crit <- -qnorm(alpha/2)
    linkinv(cbind(conf.low=pred0-crit*pred.se,
                  conf.high=pred0+crit*pred.se))
}


## prediction
## intervals from: https://stats.stackexchange.com/questions/147836/prediction-interval-for-lmer-mixed-effects-model-in-r
## dunno how to only get population-level prediction intervals from ^
#library(merTools)
test_data <- expand.grid(direction = unique(d$direction))
test_data$proba <- predict(mm1, re.form=NA, newdata = test_data, type='response')
test_data <- cbind(test_data, easyPredCI(mm1, newdata = test_data))
test_data %>% 
  ggplot(aes(x = direction, y = proba)) + 
  geom_bar(stat = 'identity') + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = .5) +
  ylim(0, 1) + 
  labs(
    x = 'Direction', 
    y = 'Probability of Selecting Safe Deck'
  ) + 
  theme_bw()
```














